dependencies {
    api(project(":application"))
    implementation(libs.hikari)
    implementation(libs.postgres)
    implementation(libs.flyway.core)
    implementation(libs.flyway.postgres)
    implementation(libs.lettuce)
    implementation(libs.bcrypt)
    implementation(libs.java.jwt)
    implementation(libs.ktor.client.core)
    implementation(libs.ktor.client.cio)
    implementation(libs.ktor.client.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.anthropic.java)
    implementation(libs.otel.api)
    implementation(libs.logback.classic)

    testImplementation(libs.testcontainers.postgres)
    testImplementation(libs.testcontainers.junit)
    testImplementation(libs.ktor.client.mock)
    testImplementation(libs.ktor.server.netty)
    testImplementation(libs.ktor.server.core)
}
